### ISSUE TITLE
Read the info paper widget

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#62] opened 2023-07-01 22:06 UTC
Recommend repurposing the Read the info paper widget and redirect to the Integration Guide and relabeling the widget DigiByte Integration Guide 2.0. Requires translation, however, the translation is already there.

The info paper can be found in the DigiByte Documentations & Guides. The DigiByte Community info paper v1.0 was written in 2019. It’s one of my favorite reads when it comes to DigiByte chronology, however, it is outdated such as Odocrypt being ASIC resistant and it will need to be updated when v8.22.0 is complete. For now, my recommendation is to change the widget to the DigiByte Integration Guide v2.0, so that it’s one of the first things that mining pools, exchanges, wallet providers and other services see when they visit the site, especially with changes from 7.17.3 to v8.22.0, such as RPC calls.

(1/3 Read the info paper widget)
![Screenshot 2023-07-01 120311](https://github.com/DigiByte-Core/DGBio/assets/136190014/83c65ade-e1cc-4742-a31d-3a758a2aaa20)
(2/3 Integration Guide English)
![Screenshot 2023-07-01 145745](https://github.com/DigiByte-Core/DGBio/assets/136190014/161933bb-e260-4113-8471-39b87d396b5e)
(3/3 Integration Guide Portuguese)
![Screenshot 2023-07-01 145906](https://github.com/DigiByte-Core/DGBio/assets/136190014/73007976-985d-4dee-8f17-49a7aac71ceb)

**Comment by Sbosvk** [comment] 2024-03-17 16:17
I think this needs to be discussed further. It doesn't actually say anywhere in the info paper that Odocrypt is ASIC resistant.
-What it says is that the algorithm rewrites and morphs itself every 10 days in order to "prevent ASIC dominance", which is still correct and the intended behavior regardless whether it is effectively so.
The infopaper has a lot of information and looks good. The crypto world is riddled with people who are looking for whitepapers / info papers, and I personally do not see the benefits outweighing the negative impact.

 @ycagel @JaredTate @gto90 @j50ng @saltedlolly I would love to hear your take on this.

**Comment by DGBNOOB** [comment] 2024-03-17 19:04
@Sbosvk thank you for the clarification on Odocrypt. A review of the infopaper, revise if needed and if the info is current and up to date then no need to change the website. However, in my opinion might need some updating with newer implementations not mentioned.

**Comment by Sbosvk** [comment] 2024-04-07 16:14
Will close this issue as this is something that we want to do at this time.

Thank you though, for your continued support and drive, @DGBNOOB. I think it makes more sense to have an issue to update the info paper than re-scoping this issue for that.

**Closed by Sbosvk** 2024-04-07 16:14 UTC
